
# C-t c  New Window
# C-t ,  naming
# "> exit" delete window
# C-t ;  toggle pane (before active)
# C-t o  next pane

# prefix C-b -> C-t
unbind C-b
# ESC が prefix のように振る舞う時間を 0 に
set -s escape-time 0
set -g prefix C-t
bind C-t send-prefix

# マウス操作
set -g mouse on

# 256色表示
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# 1-base-index
set -g base-index 1

## keybind {{{
###     # key list
###     tmux list-keys | grep
### `bind `   prefix ありの bind
### `bind -n` prefix なしの bind

# 設定ファイルをリロードするショートカット (Prefix + r)
set -as command-alias so='source-file $XDG_CONFIG_HOME/tmux/tmux.conf ; display "Reloaded!"'
bind r so

### Session {{{
# man tmux # -> /^CLIENTS AND SESSIONS

## new-session -> :new
bind -n M-h switch-client -n
bind -n M-l switch-client -p

## }}}
### Window {{{
# man tmux # -> /^WINDOWS AND PANES

bind -n M-n next-window
bind -n M-k previous-window
bind k previous-window

bind c new-window -c "#{pane_current_path}"
### }}}
### Pane {{{

# copy-mode-vi
setw -g mode-keys vi
bind v copy-mode
# v, V, C-V で選び始め
## (WSL2 + Ubuntu + Tmux のコピーに関しては別記)
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X begin-selection\; send-keys -X rectangle-toggle
# UTF-16 に変換し bomb <feff> を sed で消去 -> clip.exe
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \
"iconv -f utf-8 -t utf-16le | sed '1s/^\xFF\xFE//' | clip.exe"

## my-vim mapping
bind-key -T copy-mode-vi n send-keys -X cursor-down
bind-key -T copy-mode-vi k send-keys -X cursor-up
bind-key -T copy-mode-vi C-n send-keys -X search-again
bind-key -T copy-mode-vi C-k send-keys -X search-reverse
bind-key -T copy-mode-vi L   send-keys -X end-of-line
bind-key -T copy-mode-vi H   send-keys -X start-of-line
bind-key -T copy-mode-vi u   send-keys -X previous-paragraph
bind-key -T copy-mode-vi e   send-keys -X next-paragraph

# choose-tree (prefix + w, prefix + s)
bind-key -T root n if -F "#{==:#{pane_mode},tree-mode}" "send j" "send n"

### }}}

# next-prompt
# previous-prompt

## }}}
# status bar {{{

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g set-titles on
set -g set-titles-string "#={pane_title}"

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g window-status-current-format "#[fg=${cyan_soft},bold] ● #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 📌 ,}"
set -g window-status-format " #I:#W"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"

# active-pane の枠がちょっとだけ目立つ
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"

set -g status-interval 2
set -g status-right "#[fg=cyan,bg=default]#(~/.config/tmux/pc-info.sh) #[fg=yellow]| %H:%M "

# }}}

