
# C-t c  New Window
# C-t ,  naming
# "> exit" delete window
# C-t ;  toggle pane (before active)
# C-t o  next pane

# prefix C-b -> C-t
unbind C-b
# ESC が prefix のように振る舞う時間を 0 に
set -s escape-time 0
set -g prefix C-t
bind C-t send-prefix

# マウス操作
set -g mouse on

# 256色表示
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# 1-base-index
set -g base-index 1


## keybind {{{
###     # key list
###     tmux list-keys | grep
### `bind `   prefix ありの bind
### `bind -n` prefix なしの bind

# 設定ファイルをリロードするショートカット (Prefix + r)
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf ; display "Reloaded!"


bind -n M-n next-window
bind -n M-k previous-window

## }}}

